### ISSUE TITLE
How to run this on M1 Mac?

### ISSUE THREAD

**Issue by christianrank** [phandasm/waveform#16]
Hi,

I downloaded the Arm64 version of the plugin, but I'm getting this error:

> 20:04:27.107: os_dlopen(/Library/Application Support/obs-studio/plugins/waveform/bin/libwaveform.so-/Library/Application Support/obs-studio/plugins/waveform/bin/libwaveform.so): dlopen(/Library/Application Support/obs-studio/plugins/waveform/bin/libwaveform.so, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/waveform/bin/libwaveform.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

When I try the X64 version, OBS crashes on startup.

**Comment by phandasm** [comment]
I'm guessing you're running OBS under x86 emulation (rosetta)?
I may have misunderstood the situation on the M1s if so.

The x64 version crashes because it requires AVX which rosetta can't emulate.
1.3 works because AVX wasn't mandatory in that version.

1.4 will work if you can use a native ARM build of OBS, I'll have to look into building universal binaries to avoid this.

**Comment by christianrank** [comment]
> I'm guessing you're running OBS under x86 emulation (rosetta)?

Yes that's correct. I think there is no native arm64 version of OBS out yet.

**Comment by phandasm** [comment]
Well I ended up just swapping the x64 build on the release page, It *should* work with rosetta now.
