### ISSUE TITLE
Ubuntu 22.04.1 LTS unmet dependencies 

### ISSUE THREAD

**Issue by oparada1988** [phandasm/waveform#28]
unmet dependencies when attempting to install the deb file

![Screenshot from 2022-09-12 09-31-06](https://user-images.githubusercontent.com/4031078/189667263-d7b9a01a-4e49-41cb-84a6-dfb601455269.png)

**Comment by phandasm** [comment]
Try `sudo dpkg -i ./Waveform_v1.5.0_Ubuntu_x86_64.deb`
Looks like apt has found another package called 'waveform' somewhere so I should probably rename the package to avoid confusion.

I'm not sure what's causing the libobs conflict though?
It definitely works on both 20.04 and 22.04 using dpkg, and I just tried using apt to install it on 22.04 and didn't get the libobs conflict (I did get a different complaint but it still installed).

**Comment by oparada1988** [comment]
sudo dpkg -i ./Waveform_v1.5.0_Ubuntu_x86_64.deb 
[sudo] password for oscar: 
Selecting previously unselected package waveform.
(Reading database ... 321618 files and directories currently installed.)
Preparing to unpack .../Waveform_v1.5.0_Ubuntu_x86_64.deb ...
Unpacking waveform (1.5.0) ...
dpkg: dependency problems prevent configuration of waveform:
 waveform depends on libobs0 (>= 23.2.1); however:
  Package libobs0 is not installed.

dpkg: error processing package waveform (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 waveform

**Comment by phandasm** [comment]
Odd, did you install OBS directly from the package manager or did you get it from somewhere else?
My guess is the libobs you have is not the one from the default ubuntu package (and whatever OBS you have is preventing it from being installed because it would conflict).

In any case making waveform depend on obs-studio rather than directly on libobs probably solves this.
I've replaced the deb package on the release page, let me know if that one works.

**Comment by oparada1988** [comment]
New .deb file worked. With regarding OBS im using the official PPA for ubuntu straing from their download page.

**Comment by phandasm** [comment]
Ah, forgot about their PPA, oops.
Seems to be sorted out now so I'll go ahead and close this.
