### ISSUE TITLE
Symmetrical radial display

### ISSUE THREAD

**Issue by z0w13** [phandasm/waveform#30]
It'd be nice to have a symmetrical radial display, so basically the waveform being half a circle and then that being reflected to form a full circle. 

This is quite a common type of display on YouTube videos that are just music for one, and it does (IMO) look nicer than just radial.

For example Trap Nation uses something like this albeit extra flashy https://youtu.be/px7sQD8w_hg?t=65

**Comment by phandasm** [comment]
Hm, that's not a bad idea.
Should be pretty simple to implement too, I'll do some tests.

**Comment by proactivematter** [comment]
This is how I had the original Spectralizer plug-in set up. In fact, it's still my configuration - I couldn't do the same with Waveform, so I came here to ask that it be reimplemented. Seems I'm not alone.

I would go further and say that the Semi-Circle option in Spectralizer is fantastic since it allows you to really get creative on how you use it.

I also think the settings on the original Spectralizer were way easier to understand and configure....

Sorry @phandasm ! I don't mean to critize your work on Waveform, just sharing my perspective.

At this point you may be wondering why I don't just keep on using Spectralizer. Answer is that I now need it to be Mac compatible, which Spectralizer isn't and Wafeform is :)

**Comment by phandasm** [comment]
@proactivematter No worries, you make some perfectly valid points.

I was actually already planning to add an arc length control for radial mode alongside OP's request, so don't worry about that one.  
As for the settings panel being a convoluted mess, I'm aware but it's also kind of too late at this point. I also think it maximizes configurability for those that know what all the knobs do, so at least there's a silver lining to it.

Still recovering from an illness or these'd probably be done already, hopefully I can get to it soon(TM).
