### ISSUE TITLE
Not compatible with macOS 13.0 and OBS 28.1.2?

### ISSUE THREAD

**Issue by tylerjolson** [phandasm/waveform#31]
Doesn't seem to be recognized as a source anymore in OBS after updating. Sorry if this was something you were already aware of!

**Comment by phandasm** [comment]
Huh, is the mac x86 or ARM? What version of waveform are you using?
OBS changelog doesn't look like it should have broken anything but I don't have a good way of testing mac builds atm.

**Comment by npr77** [comment]
Same here. M1 Air, Ventura 13.0.1, OBS 28.1.2 - installed the pkg, OBS has no new sources to add.

**Comment by phandasm** [comment]
I really don't see anything that should have broken since OBS 28.0, which I know works with waveform 1.5.
Are you sure you got the right architecture (ARM waveform with ARM OBS or x86 waveform with x86 OBS)?
Also, the binaries are not signed so it might be necessary to adjust your security settings to allow waveform to run.

Unfortunately I just don't have a way to troubleshoot Mac issues atm, so if anyone can pinpoint the problem it'd be a huge help.

**Comment by npr77** [comment]
"Have you tried turning it off and on again?" :)

I just deinstalled and reinstalled OBS and now it's there!

Waveform_v1.5.0_MacOS_arm64.pkg
obs-studio-28.1.2-macos-arm64.dmg

Thanks and sorry for the noise!

**Comment by phandasm** [comment]
Weird. Nice to have confirmation it still works, though.

I'm gonna assume OP's case is similar and close this, let me know if not and I'll reopen it.
