### ISSUE TITLE
Flatpak not found

### ISSUE THREAD

**Issue by coreybruce** [phandasm/waveform#46]
Hey I just wanted to report a issue that I can't find the flatpak
```
flatpak install flathub com.obsproject.Studio.Plugins.waveform   ✔ 
Looking for matches…
error: Nothing matches com.obsproject.Studio.Plugins.waveform in remote flathub
````

it shouldn't matter what distro I am on (thats the whole point of flatpaks lol) but I already use flatpak for OBS and other packages so I know flatpak is working but I have no idea whats happening or if this is a issue or not so I wanted to report it.

**Comment by coreybruce** [comment]
only way you can install the addon is on gnome software under OBS where you can see the addons when you scroll down atm

**Comment by phandasm** [comment]
Oops, I just noticed the problem.
There's a slight typo in the flatpak command, it should actually be
`flatpak install flathub com.obsproject.Studio.Plugin.waveform` (notice 'Plugin' rather than 'Plugins').
Not sure if this is specific to Ubuntu but my test system apparently autocorrects it to the nearest match which I guess explains how it went undetected this long.

Tested just now and it seems fine.
