### ISSUE TITLE
No option to separate bars in stereo mode

### ISSUE THREAD

**Issue by JonasBjordal** [phandasm/waveform#7]
It said on the Spectralizer plugin site that the creator had decided to deprecate that project due to Waveform having more options, but I'm really missing the ability to control the separation of the bars of the opposing stereo channels from each other. Same goes for the rounded edges interacting weirdly with using alpha channels or gradients as well.

**Comment by phandasm** [comment]
Adding channel spacing is no problem and I hadn't noticed the alpha issue before, but what's wrong with gradients?
I'm guessing you want the caps to be completely in the 'saturation' range?

**Comment by JonasBjordal** [comment]
The rounded edges don't have the matching alpha value, so if you for example have a gradient of white fading into a transparent white the caps will stick out a lot with no transparency.

**Comment by phandasm** [comment]
So it's just an alpha issue? Nothing specific to the gradient?
I do see that there's an issue with the alpha due to the caps overlapping the bars (this was a fix for distortion issues in radial mode), but the caps otherwise have correct alpha.
Is that what you're talking about?

In any case it'll have to stay that way in radial mode due to the distortion, but I can fix it in the other modes at least.

**Comment by JonasBjordal** [comment]
Yeah just an alpha overlap adding up

**Comment by phandasm** [comment]
Channel spacing added and alpha overlap fixed (minus radial mode) as of 1.3.0
